version: '3.9'

services:
  culqi_database:
    container_name: culqi_database
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_volume:/data/db

  nodejs_app:
    container_name: nodejs_app
    build: .
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://culqi_database:27017
    depends_on:
      - culqi_database

volumes:
  db_volume: {}